"""Thread-safe in-memory store for conversation state tracking and reply handling."""

from __future__ import annotations

import threading
from typing import Dict, List, Optional
from app.api.schemas import ReplyRequest, ReplyResponse
from app.conversation.models import (
    ConversationEntity,
    ConversationState,
    ConversationTurn,
    TransitionResult,
)
from app.conversation.state_machine import process_turn


class ConversationStore:
    """Thread-safe registry of active conversations with atomic state transitions."""

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._conversations: Dict[str, ConversationEntity] = {}

    def get_or_create(
        self,
        conversation_id: str,
        merchant_id: Optional[str] = None,
        customer_id: Optional[str] = None,
        target_scope: str = "merchant",
        now: str = "",
    ) -> ConversationEntity:
        """Fetch or create a conversation entity under lock."""
        with self._lock:
            if conversation_id not in self._conversations:
                self._conversations[conversation_id] = ConversationEntity(
                    conversation_id=conversation_id,
                    merchant_id=merchant_id,
                    customer_id=customer_id,
                    target_scope=target_scope,
                    state=ConversationState.WAITING,
                    turn_count=0,
                    consecutive_auto_replies=0,
                    last_updated_at=now,
                )
            entity = self._conversations[conversation_id]
            if merchant_id and not entity.merchant_id:
                entity.merchant_id = merchant_id
            if customer_id and not entity.customer_id:
                entity.customer_id = customer_id
            return entity

    def record_tick_send(
        self,
        conversation_id: str,
        merchant_id: Optional[str],
        customer_id: Optional[str],
        target_scope: str,
        trigger_id: str,
        send_as: str,
        body: str,
        now: str,
    ) -> None:
        """Record an outbound message generated by Phase 4 tick."""
        with self._lock:
            entity = self.get_or_create(
                conversation_id=conversation_id,
                merchant_id=merchant_id,
                customer_id=customer_id,
                target_scope=target_scope,
                now=now,
            )
            entity.trigger_id = trigger_id
            entity.turn_count += 1
            entity.turns.append(
                ConversationTurn(
                    turn_number=entity.turn_count,
                    from_role=send_as,
                    message=body,
                    received_at=now,
                    is_auto=False,
                    action_taken="send",
                )
            )
            entity.last_action = "send"
            entity.last_updated_at = now

    def process_turn(self, request: ReplyRequest) -> TransitionResult:
        """Process turn and return structured transition and route."""
        with self._lock:
            entity = self.get_or_create(
                conversation_id=request.conversation_id,
                merchant_id=request.merchant_id,
                customer_id=request.customer_id,
                now=request.received_at,
            )
            return process_turn(
                entity=entity,
                message=request.message,
                from_role=request.from_role,
                received_at=request.received_at,
                turn_number=request.turn_number,
            )

    def process_reply(self, request: ReplyRequest) -> ReplyResponse:
        """Process an inbound reply synchronously under lock."""
        with self._lock:
            result = self.process_turn(request)
            return ReplyResponse(
                action=result.action,
                wait_seconds=result.wait_seconds,
                body=result.body,
                cta=result.cta,
                rationale=result.rationale,
            )

    def get(self, conversation_id: str) -> Optional[ConversationEntity]:
        """Fetch conversation entity copy under lock."""
        with self._lock:
            return self._conversations.get(conversation_id)

    def clear(self) -> None:
        """Reset conversation store."""
        with self._lock:
            self._conversations.clear()
